import 'dotenv/config';

import { PricingCategory, PrismaClient, UserType } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});

const prisma = new PrismaClient({ adapter });

export const DASHBOARD_MODULE_ID = 13;
export const USER_MODULE_ID = 14;
export const LEAD_MODULE_ID = 15;
export const SETTINGS_MODULE_ID = 16;
export const CONTACT_MODULE_ID = 17;
export const ACCOUNT_MODULE_ID = 18;
export const NOTE_MODULE_ID = 19;
export const ATTACHMENT_MODULE_ID = 20;
export const TASK_MODULE_ID = 22;
export const CALL_MODULE_ID = 23;
export const MEETING_MODULE_ID = 24;
export const IMPORT_MODULE_ID = 25;
export const EMAIL_MODULE_ID = 26;
export const WHATSAPP_MODULE_ID = 27;
export const GOOGLE_MODULE_ID = 28;
export const LINKEDIN_MODULE_ID = 29;
export const FACEBOOK_AND_INSTAGRAM_ADS_MODULE_ID = 31;
export const ROLE_CONFIG_MODULE_ID = 32;
export const DEAL_MODULE_ID = 33;
export const PRICING_MODULE_ID = 34;
export const COMPANY_MODULE_ID = 35;
export const PAYMENT_MODULE_ID = 36;
export const ROLE_MODULE_ID = 37;

const crud = ["View", "Create", "Edit", "Delete"];

const modules = [
  {
    id: DASHBOARD_MODULE_ID,
    name: 'Dashboard',
    path: '/dashboard',
    icon: 'GridIcon',
    description: 'Dashboard module',
    parent_id: null,
    sort_order: 1,
    activeOn: ['/dashboard'],
    availableActions: ["View"],
    showInNavbar: true,
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.AUTOMATION_ANALYTICS,
    pricingLabel: 'CRM Dashboard',
    pricingOrder: 1,
    allowedUserTypes: [UserType.ADMIN, UserType.USER],
  },
  {
    id: USER_MODULE_ID,
    name: 'Users',
    path: '/user',
    icon: 'UserCircleIcon',
    description: 'User management',
    parent_id: null,
    sort_order: 2,
    activeOn: ['/user', '/user/:id', '/user/:id/edit'],
    availableActions: crud,
    showInNavbar: true,
    showActions: false,
    allowedUserTypes: [UserType.USER],

    pricingEnabled: true,
    pricingCategory: PricingCategory.CRM,
    pricingLabel: 'User Management',
    pricingDescription: 'Manage user accounts',
    pricingOrder: 1,
  },
  {
    id: COMPANY_MODULE_ID,
    name: 'Company',
    path: '/companies',
    icon: 'UserCircleIcon',
    description: 'Companies management',
    parent_id: null,
    sort_order: 2,
    activeOn: ['/companies', '/companies/:id', '/companies/:id/edit'],
    availableActions: [],
    showInNavbar: true,
    showActions: false,
    allowedUserTypes: [UserType.ADMIN],
  },
  {
    id: PRICING_MODULE_ID,
    name: 'Pricing Plan',
    path: '/pricing-plans',
    icon: 'BadgeIndianRupee',
    description: 'Pricing Plan management',
    parent_id: null,
    sort_order: 3,
    activeOn: ['/pricing-plans', '/pricing-plans/:id', '/pricing-plans/:id/edit'],
    availableActions: [],
    showInNavbar: true,
    showActions: false,
    allowedUserTypes: [UserType.ADMIN],
  },
  {
    id: LEAD_MODULE_ID,
    name: 'Leads',
    path: '/leads',
    icon: 'ListIcon',
    description: 'Lead management',
    parent_id: null,
    sort_order: 4,
    activeOn: ['/leads', '/leads/:id', '/leads/:id/edit', '/leads/create'],
    availableActions: crud,
    showInNavbar: true,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.CRM,
    pricingLabel: 'Lead Management',
    pricingDescription: 'Manage and track your sales leads',
    pricingOrder: 1,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: CONTACT_MODULE_ID,
    name: 'Contact',
    path: '/contacts',
    icon: 'Contact',
    description: 'Contact management',
    parent_id: null,
    sort_order: 5,
    availableActions: crud,
    activeOn: [
      '/contacts',
      '/contacts/:id',
      '/contacts/:id/edit',
      '/contacts/create',
    ],
    showInNavbar: true,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.CRM,
    pricingLabel: 'Contact Management',
    pricingDescription: 'Manage your customer contacts',
    pricingOrder: 2,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: NOTE_MODULE_ID,
    name: 'Note',
    path: '/notes',
    icon: 'NotebookPen',
    description: 'Notes management',
    parent_id: null,
    sort_order: 6,
    availableActions: crud,
    activeOn: [
      '/notes',
      '/notes/:id',
      '/notes/:id/edit',
      '/notes/create',
    ],
    showInNavbar: false,
    showActions: true,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: ATTACHMENT_MODULE_ID,
    name: 'Attachment',
    path: '/attachments',
    icon: 'Paperclip',
    description: 'Attachments management',
    parent_id: null,
    sort_order: 7,
    availableActions: crud,
    activeOn: [
      '/attachments',
      '/attachments/:id',
      '/attachments/:id/edit',
      '/attachments/create',
    ],
    showInNavbar: false,
    showActions: true,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: ACCOUNT_MODULE_ID,
    name: 'Accounts',
    path: '/accounts',
    icon: 'BookUser',
    description: 'Account management',
    parent_id: null,
    sort_order: 8,
    availableActions: crud,
    activeOn: [
      '/accounts',
      '/accounts/:id',
      '/accounts/:id/edit',
      '/accounts/create',
    ],
    showInNavbar: true,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.CRM,
    pricingLabel: 'Account Management',
    pricingDescription: 'Manage customer and business accounts',
    pricingOrder: 3,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: DEAL_MODULE_ID,
    name: 'Deal',
    path: '/deals',
    icon: 'HeartHandshake',
    description: 'Deal management',
    parent_id: null,
    sort_order: 9,
    activeOn: ['/deals', '/deals/:id', '/deals/:id/edit', '/deals/create'],
    showInNavbar: true,
    availableActions: crud,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.CRM,
    pricingLabel: 'Deal Pipeline',
    pricingDescription: 'Manage your sales opportunities and pipelines',
    pricingOrder: 4,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: TASK_MODULE_ID,
    name: 'Tasks',
    path: '/tasks',
    icon: 'LayersMinus',
    description: 'Task management',
    parent_id: null,
    sort_order: 10,
    availableActions: crud,
    activeOn: [
      '/tasks',
      '/tasks/:id',
      '/tasks/:id/edit',
      '/tasks/create',
    ],
    showInNavbar: true,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.COMMUNICATION,
    pricingLabel: 'Tasks & Activities',
    pricingOrder: 1,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: CALL_MODULE_ID,
    name: 'Calls',
    path: '/calls',
    icon: 'PhoneCall',
    description: 'Task management',
    parent_id: null,
    sort_order: 11,
    availableActions: crud,
    activeOn: [
      '/calls',
      '/calls/:id',
      '/calls/:id/edit',
      '/calls/create',
    ],
    showInNavbar: true,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.COMMUNICATION,
    pricingLabel: 'Call Management',
    pricingOrder: 2,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: MEETING_MODULE_ID,
    name: 'Meeting',
    path: '/meetings',
    icon: 'Handshake',
    description: 'Meeting management',
    parent_id: null,
    sort_order: 12,
    availableActions: crud,
    activeOn: [
      '/meetings',
      '/meetings/:id',
      '/meetings/:id/edit',
      '/meetings/create',
    ],
    showInNavbar: true,
    showActions: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.COMMUNICATION,
    pricingLabel: 'Meeting Management',
    pricingOrder: 3,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: IMPORT_MODULE_ID,
    name: 'Imports',
    path: '/imports',
    icon: 'GridIcon',
    description: 'Bulk import management',
    parent_id: null,
    sort_order: 13,
    availableActions: ["Leads", "Contacts", "Accounts"],
    activeOn: ['/imports', '/imports/:id'],
    showInNavbar: true,
    showActions: false,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: EMAIL_MODULE_ID,
    name: 'Emails',
    path: '/emails',
    icon: 'Mail',
    description: 'Email log management',
    parent_id: null,
    sort_order: 14,
    availableActions: crud,
    activeOn: ['/emails'],
    showInNavbar: true,

    pricingEnabled: true,
    pricingCategory: PricingCategory.COMMUNICATION,
    pricingLabel: 'Email Integration',
    pricingOrder: 4,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: WHATSAPP_MODULE_ID,
    name: 'Whatsapp',
    path: '/whatsapp',
    icon: 'MessageCircleMore',
    description: 'Whatsapp chat management',
    parent_id: null,
    sort_order: 15,
    availableActions: ["Whatsapp Access"],
    activeOn: ['/whatsapp'],
    showInNavbar: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.COMMUNICATION,
    pricingLabel: 'WhatsApp Integration',
    pricingOrder: 5,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: GOOGLE_MODULE_ID,
    name: 'Google',
    path: '/google',
    icon: 'MessageCircleMore',
    description: 'Google chat management',
    parent_id: null,
    sort_order: 16,
    activeOn: ['/google'],
    showInNavbar: false,
    availableActions: ["Google Ads", "Google Calendar"],
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.MARKETING,
    pricingLabel: 'Google Ads Lead Sync',
    pricingOrder: 1,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: LINKEDIN_MODULE_ID,
    name: 'Linkedin',
    path: '/linkedin',
    icon: 'MessageCircleMore',
    description: 'Linkedin chat management',
    parent_id: null,
    sort_order: 17,
    activeOn: ['/linkedin'],
    showInNavbar: false,
    availableActions: ["Linkedin Ads"],
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.MARKETING,
    pricingLabel: 'LinkedIn Ads Lead Sync',
    pricingOrder: 2,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: FACEBOOK_AND_INSTAGRAM_ADS_MODULE_ID,
    name: 'Facebook & Instagram',
    path: '/facebook-and-instagram',
    icon: 'MessageCircleMore',
    description: 'Facebook & Instagram chat management',
    parent_id: null,
    sort_order: 18,
    activeOn: ['/facebook-and-instagram'],
    showInNavbar: false,
    availableActions: ["Facebook & Instagram Ads"],
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.MARKETING,
    pricingLabel: 'Facebook & Instagram Ads',
    pricingOrder: 3,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: ROLE_CONFIG_MODULE_ID,
    name: 'Role Configs',
    path: '/role-configs/:id/edit',
    icon: 'MessageCircleMore',
    description: 'Role Configs management',
    parent_id: null,
    sort_order: 19,
    activeOn: ['/role-configs/:id/edit'],
    showInNavbar: false,
    availableActions: [],
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.SUPPORT_SECURITY,
    pricingLabel: 'Role-based Permissions',
    pricingOrder: 1,
    allowedUserTypes: [UserType.USER],
  },
  {
    id: PAYMENT_MODULE_ID,
    name: 'Payments',
    path: '/payments',
    icon: 'HandCoins',
    description: 'Payment management',
    parent_id: null,
    sort_order: 20,
    activeOn: ['/payments', '/payments/:id'],
    showInNavbar: true,
    availableActions: ["View"],
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.FINANCE,
    pricingLabel: 'Role-based Permissions',
    pricingOrder: 1,
    allowedUserTypes: [UserType.USER, UserType.ADMIN],
  },
  {
    id: ROLE_MODULE_ID,
    name: 'Role',
    path: '/role-configs',
    icon: 'HandCoins',
    description: 'User role management',
    parent_id: null,
    sort_order: 21,
    activeOn: ['/role-configs'],
    showInNavbar: false,
    availableActions: crud,
    showActions: false,

    pricingEnabled: true,
    pricingCategory: PricingCategory.SUPPORT_SECURITY,
    pricingLabel: 'Role-based Permissions',
    pricingOrder: 1,
    allowedUserTypes: [],
  },
  {
    id: SETTINGS_MODULE_ID,
    name: 'Settings',
    path: '/settings',
    icon: 'PieChartIcon',
    description: 'Application settings',
    parent_id: null,
    sort_order: 22,
    activeOn: [
      '/settings',
      '/role-configs',
      '/role-configs/:id/edit',
      "/connects",
      "/calendar",
      "/whatsapp",
      "/facebook/lead-sync-chains",
      "/facebook/lead-sync-chains/create",
      "/google-ads/lead-sync-chains",
      "/google-ads/lead-sync-chains/create",
      "/linkedin-ads/lead-sync-chains",
      "/linkedin-ads/lead-sync-chains/create"
    ],
    availableActions: [],
    showInNavbar: true,
    showActions: false,
    allowedUserTypes: [UserType.USER],
  },
];

export default async function seedModules() {
  for (const module of modules) {
    await prisma.module.upsert({
      where: {
        path: module.path,
      },
      update: {
        name: module.name,
        icon: module.icon,
        description: module.description,
        sort_order: module.sort_order,
        parent_id: module.parent_id,
        activeOn: module.activeOn,
        showInNavbar: module.showInNavbar,
        availableActions: module.availableActions,
        showActions: module.showActions,
        pricingEnabled: module.pricingEnabled,
        pricingCategory: module.pricingCategory,
        pricingLabel: module.pricingLabel,
        pricingOrder: module.pricingOrder,
        allowedUserTypes: module.allowedUserTypes,
      },
      create: module,
    });
  }
}
